### ISSUE TITLE
Add faq on exporting media downloads

### ISSUE THREAD

**Issue by smusula** [onaio/help#101]
- Add FAQ for media downloads including .zip media attachments;
- Link it to [http://help.ona.io/faq/how-to-upload-media-files](http://help.ona.io/faq/how-to-upload-media-files/) faq

**Comment by faith-mutua** [comment]
I have written up a [draft](https://docs.google.com/a/ona.io/document/d/1rbRctKmUvQts8w9tak3ekkkTHWWqn8TRytZsqQAY6S8/edit?usp=sharing) in google docs. Please review

**Comment by smusula** [comment]
@faith-mutua please address the comments left on the Google doc @msschroeder will review and give a go ahead to convert to Markdown. Basically, as explained in person how can one access their media download? if you take a photo or record an audio as part of your question, how can you retrieve that data from Ona, hence exporting media downloads

**Comment by msschroeder** [comment]
@faith-mutua I would just link this to the data management guide when it is uploaded and not link it to how to upload media files
