### ISSUE TITLE
Update XLS Report Documentation screenshots to reflect new UI 

### ISSUE THREAD

**Issue by smusula** [onaio/help#105]
- [X] Update XLS Report Documentation screenshots to reflect new UI; 
- [ ] Add the [Google doc](https://docs.google.com/document/d/11TvJH9Bk25QBJ_U1YhSMKavnwFT2_5K9CnzvhQ_uUrI/edit?usp=sharing) to markdown and add it as an faq;

**Comment by faith-mutua** [comment]
@smusula, working on it
