### ISSUE TITLE
Define permissions for transferring and create help site article

### ISSUE THREAD

**Issue by pld** [onaio/help#107]
From @cagulas:

1) Transfer project out of individual account

User must be project admin.

2) Transfer project out of org account

User must be project admin.

3) Transfer project into individual account

No permissions required

4) Transfer project into org account

User must be org admin or org project manager

**Comment by rowo** [comment]
The project guide has some information: http://help.ona.io/guides/projects/#transferring-projects

**Comment by cagulas** [comment]
Did we ever decide about the 2nd point?  On the site right now, it says you need to be an org admin to transfer a project out of an org, but above it says you have to be at least a project admin.  Which is it currently?  What should it be?
