### ISSUE TITLE
Remove link placeholders from help page faq

### ISSUE THREAD

**Issue by cagulas** [onaio/help#112]
Aafaque brought this to our attention.  On Ona faq about whether user should sign up for Ona account, there are two link placeholders that were never removed when the faq was published.  See below.

![screen shot 2015-11-14 at 4 34 34 pm](https://cloud.githubusercontent.com/assets/3488986/11163901/5dd9f35c-8af2-11e5-9ebb-079eda9491f4.png)

![screen shot 2015-11-14 at 4 34 10 pm](https://cloud.githubusercontent.com/assets/3488986/11163902/62be3f9a-8af2-11e5-9b94-cb846c30f373.png)

**Comment by rowo** [comment]
Just closed
