### ISSUE TITLE
Ona Collect tutorial

### ISSUE THREAD

**Issue by rowo** [onaio/help#117]
Need to add a section to http://help.ona.io/guides/data-collection/ talking about Ona Collect. This is mainly another section below the ODK Collect section where it says it behaves the same as ODK Collect, but points out the main differences: logging in, no need to configure server, and the checkbox to show/hide forms shared with the user.

**Comment by smusula** [comment]
@rowo have you started working on this?

**Comment by rowo** [comment]
@smusula No. I was waiting to see what is completed for v3. The [blog post](http://blog.ona.io/general/2015/12/02/ona-collect.html) goes over the changes to v1/v2.

**Comment by msschroeder** [comment]
@rowo I would think that now might be a good idea to include a bit on this now with the release of th e app yesterday. Thoughts?

**Comment by rowo** [comment]
@msschroeder agreed.. sometime in january at least.

**Comment by mberg** [comment]
Let's put up a very simple blog post announcing it again.

**Comment by msschroeder** [comment]
I am going to close this as it has been decided that we will be discontinuing this app and communicating this to the client.
