### ISSUE TITLE
Add info on filtered data view

### ISSUE THREAD

**Issue by rowo** [onaio/help#118]
- Why use it
- How it works
- Constraint with editing

**Comment by rowo** [comment]
@smusula can you figure out how we can get this done before Dec 14?

**Comment by smusula** [comment]
@rowo I'll start working on this tomorrow Thursday 10th.

**Comment by rowo** [comment]
@smusula thanks. Carolyn and I are available to help.

**Comment by mberg** [comment]
Is this for the help page or a blog post?

**Comment by rowo** [comment]
@mberg this is in the help repo

**Comment by smusula** [comment]
Unable to add all screenshots to the content blocked by: https://github.com/onaio/zebra/issues/3438
