### ISSUE TITLE
Application for "do-gooder" account

### ISSUE THREAD

**Issue by rowo** [onaio/help#12]

**Comment by cagulas** [comment]
hey @rowo can we discuss what types of people / orgs we're trying to target with this type of account?  Have a few ideas for an application of sorts, but wanted more specifics (if known yet) on what we're looking for.

**Comment by rowo** [comment]
So far, we've been telling people that since we're focused on the do-gooder industry, we can't offer free accounts to every Tom, Dick and Harry non-profit. The free level service should be sufficient for most users doing light data collection, so for higher level free accounts, we're looking at non-grant-funded, grassroots organizations that really need to not pay anything to have digital data collection and management.  @mberg anything more to add on specifics?

**Comment by cagulas** [comment]
I've started this document:  https://docs.google.com/document/d/1e3zqQjuSKNZv8XKMR-EdEVwI7hHYcQEUs-tJ4cz3BMs/edit

Thoughts so far?  @rowo @mberg

**Comment by cagulas** [comment]
Closing this, application is covered under: https://github.com/onaio/ona/issues/73
