### ISSUE TITLE
Add note to org members section about organization collaborators

### ISSUE THREAD

**Issue by rowo** [onaio/help#121]
Add note to org member roles that explains that an organization collaborator is a user that is shared on an organization project but isn't actually part of the organization. This can go below the table or above in the roles intro paragraph. This is so people clicking from the tooltip on https://github.com/onaio/zebra/issues/3494 understand what they are better.

http://help.ona.io/guides/organizations/#organization-member-roles

**Comment by cagulas** [comment]
How does the following sound:

"In addition to the three organization roles above, a user can also be added individually to a project within the org and become an organization collaborator.  An organization collaborator is a user that is shared on an organization project but isn't part of the organization.  When viewing the organization home page, organization collaborators will see the list of projects that they have been added to and the list of organization collaborators.  They will not be able to see the list of organization members, organization settings, or any other projects in the organization."

As @rowo stated, this can go underneath the table on its own in a paragraph or in a note section.

**Comment by smusula** [comment]
@cagulas @rowo Added the paragraph https://github.com/onaio/help/commit/ddeb22a59176af7aaa7c832979547727c26e2df3. Closing the issue.

**Comment by cagulas** [comment]
Would it be ok if I moved this paragraph underneath the table?  I think it might be better placed after the explanation of the 3 member roles.  @smusula
