### ISSUE TITLE
Add section on reviewing responses on ODK Collect before submission

### ISSUE THREAD

**Issue by smusula** [onaio/help#125]
@jmunene Add a section to http://help.ona.io/guides/data-collection/  talking about reviewing responses and editing before sending submissions using the **Go to Prompt** menu.

**Comment by smusula** [comment]
@faith-mutua Assigning you this issue.

**Comment by faith-mutua** [comment]
@smusula, working on it

**Comment by faith-mutua** [comment]
@smusula, I have done a draft on google docs https://docs.google.com/a/ona.io/document/d/1mlc2Eyyn84lPhCi9ZdkRy39-Nk9ndPU7OZ30tk40y44/edit?usp=sharing

**Comment by smusula** [comment]
Added comments to the doc, you can address them and convert the doc into markdown

**Comment by faith-mutua** [comment]
Please have a look at the [PR](https://github.com/onaio/help/pull/160)
