### ISSUE TITLE
Add content on deleting project collaborators and org members

### ISSUE THREAD

**Issue by smusula** [onaio/help#141]
Add content on the projects and organizations guides respectively on:
- [ ] Deleting project collaborators;
- [ ] Removing org members
- [ ] Leaving an organization

**Comment by faith-mutua** [comment]
Starting to work on this today

**Comment by smusula** [comment]
I've added comments, please address them

**Comment by faith-mutua** [comment]
@smusula I have addressed the comments on the draft [document](https://docs.google.com/a/ona.io/document/d/1YmFc5Uu8WIHi--AJCZoagSfPbEpYRue7wG6WDxvzw8U/edit?usp=sharing)

**Comment by smusula** [comment]
@faith-mutua I've added suggestions the content can be converted to markdown and be added to these sections https://help.ona.io/guides/organizations/#organization-members and https://help.ona.io/guides/projects/#collaborating-with-others respectively. Please ensure that clear and well highlighted screen shots as per these instructions: https://github.com/onaio/help#screenshots are taken. @msschroeder will review your PR
