### ISSUE TITLE
Add content on how to reveal inactive forms

### ISSUE THREAD

**Issue by smusula** [onaio/help#144]
Add content on how to reveal inactive forms on the project page in the **Managing forms** sections in the [forms guide](https://help.ona.io/guides/forms)

**Comment by rowo** [comment]
Note a recent change: by default, the show inactive forms checkbox is selected (so shown automatically until you turn it off).

**Comment by smusula** [comment]
Yeah, thanks for the reminder. I've added this it will reflect on my PR once I push my commits
