### ISSUE TITLE
Add faq on replacing forms if id_string is changed during upload

### ISSUE THREAD

**Issue by Santei** [onaio/help#151]
- [ ] Create faq on replacing forms if id_string is changed during upload
- [ ] Create a zebra issue to link to this FAQ

**Comment by Santei** [comment]
Associated github issue https://github.com/onaio/zebra/issues/3043

**Comment by smusula** [comment]
@Santei please provide more information what is supposed to be written here. One can replace any form wether id's match or not? What impact does this have on existing content https://help.ona.io/faq/replacing-forms-without-submissions.

What do you mean when you say `Create a zebra issue to link to this FAQ'

**Comment by Santei** [comment]
@smusula You cannot replace any form if id's do not match. 
Background information:
- When a user tries to upload a form to an account that has another form with a similar id string, the form is uploaded but the id_string is changed to ensure uniqueness. For example, you can find that the id_string has a number appended to it. This new id_string is displayed to the user upon a successful upload.
Something like `To keep your form unique, your form ID String has been updated to "new-id-string". To replace the form .... More info in our FAQ.`
This issue is about writing content explaining to users how to replace forms if the form id_string was changed during upload because of an already existing form with the same id_string.

The FAQ from the message above is a link to this faq.
So after this issue has been handled, we need to update the link in zebra to point to this FAQ.

@smusula @faith-mutua @jmunene kindly let me know if you now understand the purpose of the issue.

**Comment by faith-mutua** [comment]
@Santei, I now understand the purpose of the issue. Thanks for the clarification

**Comment by Santei** [comment]
Okay cool.

**Comment by faith-mutua** [comment]
@smusula, Please review the [draft](https://docs.google.com/a/ona.io/document/d/1skhJCIhd4XCbBNqnYY-mWzXkq11ivxUjnFnm_QHLCZw/edit?usp=sharing) on Google Docs

**Comment by smusula** [comment]
@Santei can you check the section `Duplicate form_ids not allowed in Ona` https://help.ona.io/faq/form-id  does it contradict with this issue? Or should the screenshot be replaced? then zebra should point to this faq, no?

**Comment by Santei** [comment]
@smusula I don't think it contradicts. This is documentation on how to replace a form whose id_string was changed because it was uploaded to a separate project but to an account that had the same id_string.

**Comment by smusula** [comment]
@Santei thanks for the clarification.
@faith-mutua the appending of form_id is already been mentioned here https://help.ona.io/faq/form-id, in this issue as we explained with @Santei you're to tell the users to remember to append the form_id string before they replace the form as seen in the screen shot. Please do not repeat but reference that faq and add the content as we've explained @msschroeder  will review once done
