### ISSUE TITLE
R & Ona Integration documentation

### ISSUE THREAD

**Issue by jmunene** [onaio/help#152]
Convert [this documentation]()https://docs.google.com/a/ona.io/document/d/17ggsowPSwheMmxc8HUdFTA3WBttYEyE-wfWtL5kw_m4/edit?usp=sharing to markdown and add it to the FAQ page. Follow the instrutions provided in the [readme.md](https://github.com/onaio/help) page

**Comment by smusula** [comment]
Assigning this @msschroeder @jmunene can review the PR when the markdown file is done

**Comment by msschroeder** [comment]
Closing this issue and will include a reference in the issue #76, the data management guide, to the R documentation (blog and ona.R repo).
