### ISSUE TITLE
Should we delete this faq: https://help.ona.io/faq/forgot-email-address

### ISSUE THREAD

**Issue by smusula** [onaio/help#156]
@rowo let me know your thoughts on the first line of this faq `If you know the account username, we can email you the email address used to register the account.`  We had previously said that we won't share the entire email as per this [internal support guideline doc](https://docs.google.com/document/d/1KxbaPxBZim5KUsksOXRGoCfxi1E2GEjTKFNX6EgVUQA/edit#), i.e we won't include the email domain but something like r****@***.*o

**Comment by rowo** [comment]
@smusula Yeah, that's not a correct first line. This page isn't useful. Though some info in this page should be part go in an overall Login Troubleshooting/help page.
