### ISSUE TITLE
Add documentation on Services, Basemaps

### ISSUE THREAD

**Issue by smusula** [onaio/help#157]
Add documentation on:
- [X] Apps
  - [X] Rapidpro, Textit
  - [X] Google sheets
- [X]  Basemaps
- [X] Add documentation on how Services and Web hooks work on Ona

**Comment by smusula** [comment]
@faith-mutua the ona-apps page is now added you can now add the Google sheets & Rapidpro finalized markdown content to https://github.com/onaio/help/tree/157-ona-apps. Please set the guide published to false, until all these two are added.

**Comment by pld** [comment]
@bmalina I noticed the webhook was reverted, what's the status of this?

**Comment by bmalina** [comment]
@pld the documentation is still under review with Meghan.

**Comment by msschroeder** [comment]
closed with PR #206 and PR #203
