### ISSUE TITLE
Add remaining starter forms to help site and link to betatester account

### ISSUE THREAD

**Issue by rowo** [onaio/help#16]
Forms should be public but not editable
- can only download/clone forms

Can use Ona support for new features

**Comment by cagulas** [comment]
We have 10 forms in a 'Starter Forms' project on the betatester account.  We can add to this over time.  Where can we reference these starter forms on the help site?  I think the original idea was to list the forms and provide examples of advanced features illustrated in each form.

**Comment by rowo** [comment]
I started a page on the help site: http://help.ona.io/faq/starter-forms/ that we can make more prominent once complete. We can add links to the betatester account from there too.

**Comment by cagulas** [comment]
Ok, have updated the name of this issue.  

https://drive.google.com/drive/u/1/folders/0B3F9Fte7ey_wbXRST0RUOFNHdUk/0B3F9Fte7ey_wSDBBQTFZYWxuWjQ/0B2klGJhO-wEqYTg0XzNWS25RSEk/0BzZ4hMHTat-YRjBoZEJIclpjYWM/0B3wlsuQEG5hyZWhDN0VUSG94LWc/0B2klGJhO-wEqV2lKZXhQZ0diWjg

That's the folder on drive where the starter forms are at and the document that categorizes them.  

Use existing template currently on help site.

**Comment by cagulas** [comment]
Will work on this next week.

**Comment by cagulas** [comment]
https://github.com/onaio/help/pull/54

This PR adds 4 more starter forms to this faq.  

@rowo  how do we want to 'link the betatester' account to this faq?  Just a line at the top or bottom somewhere?

**Comment by rowo** [comment]
At the top is good, mentioning they can find all of the forms there. And example data if it exists to explore. Are the forms all in one project?

**Comment by cagulas** [comment]
Closing with https://github.com/onaio/help/pull/54

@rowo yes, these are currently all in one project that is public that is called Starter Forms.
