### ISSUE TITLE
Include step on picking project owner in project creation guide

### ISSUE THREAD

**Issue by cagulas** [onaio/help#162]
The project guide, specifically the section on creating new projects, was authored before we had the ability to choose project owner in a dropdown menu, see here: https://help.ona.io/guides/projects/#create-a-project.  We need to add the step about being able to choose the project owner in the dropdown.

**Comment by faith-mutua** [comment]
@smusula, I have written up a [draft](https://docs.google.com/a/ona.io/document/d/1YhGjeJqL5kG5dHr8yXiBtg_dQR9cFGS4UK4z1rcDAjI/edit?usp=sharing) for this on Google Docs

**Comment by smusula** [comment]
@faith-mutua I've added comments, please address them

**Comment by faith-mutua** [comment]
@smusula, I have addressed the comments on this [document](https://docs.google.com/a/ona.io/document/d/1YhGjeJqL5kG5dHr8yXiBtg_dQR9cFGS4UK4z1rcDAjI/edit?usp=sharing)

**Comment by smusula** [comment]
@faith-mutua add this as step 4 of https://help.ona.io/guides/projects/#create-a-project, please ensure you're using the same project as the one in the guide: https://ona.io/acme/2280.  See my comments in the Google doc, the text is fine but the screen shot needs to be replaced as per my comments. Then convert to an MD file and assign the PR to @msschroeder
