### ISSUE TITLE
Remove what's new in ona Link or link it to release notes on zebra?

### ISSUE THREAD

**Issue by royrutto** [onaio/help#165]
<img width="201" alt="screen shot 2016-05-12 at 9 51 00 am" src="https://cloud.githubusercontent.com/assets/1002419/15206358/31946968-1827-11e6-9afd-fa130f9c0cd6.png">

What's new in ona? on https://help.ona.io should be remove or linked to the release notes page on https://ona.io/release-notes.html instead

**Comment by rowo** [comment]
https://help.ona.io/faq/new-in-ona this link

**Comment by msschroeder** [comment]
#155

**Comment by msschroeder** [comment]
@rowo with the new helpsite, I don't think we will need to include the what's new in Ona page.
