### ISSUE TITLE
Update helpsite with content when a user can't save to dashboard

### ISSUE THREAD

**Issue by skambo** [onaio/help#168]
- The help site should be updated with information on when a user can't save to dashboard and why, refer to https://github.com/onaio/zebra/issues/4009
- A user has asked about the same, related helpscout issue https://secure.helpscout.net/conversation/208891910/3032/?folderId=488736

**Comment by faith-mutua** [comment]
@smusula; I think this should be included in the [Data Management Guide](https://docs.google.com/a/ona.io/document/d/14Y6CwTzZv1UnwyPM-u67SWU5OvA3apOSVnqm2Cb2UrI/edit?usp=sharing) that you are working on.

**Comment by smusula** [comment]
Will be covered in this guide: https://github.com/onaio/help/issues/76
