### ISSUE TITLE
Create a design for Ona Apps

### ISSUE THREAD

**Issue by smusula** [onaio/help#174]
Create a design for Ona Apps I'll be adding Google sheets, Rapidpro content on this page

**Comment by rowo** [comment]
@smusula To confirm when you say "design" you are talking about an icon for an Ona Guide like one of the below?

<img width="568" alt="screen shot 2016-07-19 at 8 19 23 am" src="https://cloud.githubusercontent.com/assets/1584163/16949577/8cd9bcdc-4d89-11e6-8c6b-1d57a380672e.png">

**Comment by smusula** [comment]
yes an icon

**Comment by rowo** [comment]
@smusula here you go

![ona-apps](https://cloud.githubusercontent.com/assets/1584163/16972892/092300aa-4dfd-11e6-88b6-9732493e9c12.png)

**Comment by pld** [comment]
is the text on an angle in that icon? Doesn't t look like "Apps" is sloping up?

**Comment by rowo** [comment]
Intersting.

**Comment by rowo** [comment]
Here's the fixed one. I think my monitor is tilted. Thanks for catching that @pld.

![ona-apps](https://cloud.githubusercontent.com/assets/1584163/16975333/395fcefe-4e13-11e6-8821-678290248b2b.png)

**Comment by mberg** [comment]
This is hilarious.  We should throw this up on a blog post! Called tilted
monitor and post it to hacker news
