### ISSUE TITLE
Add pricing faqs to help site

### ISSUE THREAD

**Issue by cagulas** [onaio/help#182]
Here's a list of pricing-related faqs that I think would be useful on the help site, based on common questions I've encountered handling sales:

What's the difference between a personal and organization account?
What's the difference between a public and private project?
What's the difference between an org member and a project collaborator?
**How do I pay?**
**Is there an annual commitment?**
**Is there a discount if I pay annually?**
**Are Enketo webforms included in my plan?**
**How do I cancel my subscription?**
**How do I change my plan?**
**What happens when my account is downgraded?**
**What level of support do I get with my plan?**
**I have multiple accounts. How do I know which account to upgrade?**
**How do I upgrade my org account?**
**What are the limits on the free plan?**
**What happens if I go over my plan limits?**

Some of these are already up, but require some edits/improvements/re-naming the faq. The ones in bold I think can be organized in a specific pricing section in the list of faqs on the site.

Thoughts?

**Comment by rowo** [comment]
Nice list! Maybe a few top ones can be put into a pricing faq, and the rest can go into https://help.ona.io/guides/user-accounts/? I think it's conventional to put pricing/paid plan documentation into a top level "Account" section.

**Comment by cagulas** [comment]
Ok, cool. So update the user accounts guide and then pull out the top faqs into a short pricing or account faq section.

**Comment by cagulas** [comment]
User account guide is updated with upgrading information: https://help.ona.io/guides/user-accounts/.

Next I'll work on the remaining faqs.

**Comment by COpenda** [comment]
@msschroeder Is this still needed? Some of these questions are already FAQ's on the help site and the plans page has pretty much covered the other questions. Please let me know if there are specific questions that need content and I can update those.

**Comment by msschroeder** [comment]
@rowo @cagulas I think this might be a better question for Roger and Carolyn. Would you still like a pricing faq. Many of this questions no longer seem relevant after updating the plans page.

**Comment by rowo** [comment]
@COpenda @msschroeder If you've gone through and everything is covered that needs to be from support and sales perspectives regarding payment, it is fine with me to close the issue. 

The goal is to reduce answering the same question over and over — so if that's already happening, that's great. Also note we're moving to the new help site soon.
