### ISSUE TITLE
Add content for creating an XSLForm and import data from a CSV file

### ISSUE THREAD

**Issue by skambo** [onaio/help#188]
Support documentation will be necessary for this feature that is currently being worked on https://github.com/onaio/zebra/issues/4299#issuecomment-240931252

**Comment by msschroeder** [comment]
@royrutto @rowo Can you review the help documentation for this feature. A few images may need to be changed depending on pending changes. 

Google Doc: https://docs.google.com/document/d/1-tr8W5P8-7NgmNpCyn-o2NCAUnXPEoFmgdrmEkXTIUI/edit

**Comment by msschroeder** [comment]
Closed with PR #221
