### ISSUE TITLE
Update help site favicon and copyright year

### ISSUE THREAD

**Issue by cagulas** [onaio/help#189]
As you can see in the below screenshot, the favicon for the help site and the favicon for the main Ona site are different. Should these be the same?

![screen shot 2016-08-29 at 2 43 08 pm](https://cloud.githubusercontent.com/assets/3488986/18050455/5209e9f4-6df7-11e6-8eba-e4f87a8855d6.png)

Also, the help site still says 2014, see below:

![screen shot 2016-08-29 at 2 43 28 pm](https://cloud.githubusercontent.com/assets/3488986/18050472/69c750ea-6df7-11e6-81dc-3e992c31bbc5.png)

**Comment by rowo** [comment]
Sure

**Comment by skambo** [comment]
On the footer of blog.ona.io as well

![screen shot 2016-09-02 at 4 18 00 pm](https://cloud.githubusercontent.com/assets/4996911/18205093/e4fc9386-7128-11e6-9d00-c2e9ff501a53.png)

**Comment by msschroeder** [comment]
MS: Changes were made
