### ISSUE TITLE
FAQ to link a form or a dataview as a media file to another form

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#191]
Develop a faq briefly explaining feature noted in [zebra issue #4284](https://github.com/onaio/zebra/issues/4284)

**Comment by faith-mutua** [comment]
[PR](https://github.com/onaio/help/pull/193/files) on review.

**Comment by msschroeder** [comment]
Closed with [merge] (https://github.com/onaio/help/pull/193/files)
