### ISSUE TITLE
Add an FAQ for vector tile support

### ISSUE THREAD

**Issue by skambo** [onaio/help#194]
Maps on Zebra will soon be switched to use vector tiles.

For users using functionality like basemaps, they won't work with the new maps. @royrutto says they will have to use vector tile basemaps. So an explanation for this may be necessary..

**Comment by mberg** [comment]
We'll need to update the basemap code to support the different format that
vector maps uses.  This is good since it was difficult to add the old
basemaps now anyways.

Vector maps don't work on older browsers so we'll need to tell people to
use a modern browser like chrome

**Comment by msschroeder** [comment]
closed with PR #206
