### ISSUE TITLE
Add content on Ona's Security Features 

### ISSUE THREAD

**Issue by COpenda** [onaio/help#195]
There's no content available on the security features we offer.

`Ona secures your data while at rest in our data centres and in transit using AES-256 encryption. All our forms are also encrypted, HTTPS for server-client connections and A+ certified server-client SSL configuration. We are also ISO 27001 certified via AWS data centres`

Perhaps a whole guide on security? That also includes privacy and security features like filtered datasets and permission levels?

**Comment by rowo** [comment]
related: https://github.com/onaio/ona/issues/78

**Comment by msschroeder** [comment]
Is [issue 57] (https://github.com/onaio/help/issues/57) something we can combine with this guide as well. I think it would fit in well.

**Comment by msschroeder** [comment]
Google Doc: https://docs.google.com/document/d/1aIxOmGq-MsaZS8pdBcWJaRaXnOROxiNq6341p8z1m4A/edit#heading=h.7mv8zfqlmyiy

**Comment by msschroeder** [comment]
Closed with PR #244
