### ISSUE TITLE
Add FAQ on meta permission levels

### ISSUE THREAD

**Issue by faith-mutua** [onaio/help#197]
Users on the WHO DCP platform will soon be transitioned over to the Ona version. WHO DCP has a few custom features with permissions that were added with funding from the client. They have requested that these features be added to the Ona hosted version to ensure a smooth transition for them. 

As a result, we need content for these features on the help site before they are rolled out. Refer to this ticket https://github.com/onaio/zebra/issues/4459 for more information

**Comment by rowo** [comment]
@bmalina Do you plan to work on this this week?

**Comment by bmalina** [comment]
@rowo just making a few changes after review, it should be ready by tomorrow.
