### ISSUE TITLE
Add content for new map features as an FAQ 

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#210]
[ ] Hexbin support to maps ([Core Issue 4642] (https://github.com/onaio/zebra/issues/4642))
[ ] Heat map support to maps ([Core Issue 4461] (https://github.com/onaio/zebra/issues/4641))

Link content to basemap faq on help site: https://help.ona.io/faq/adding-a-basemap

**Comment by bmalina** [comment]
Closing this. Posted on the new help site.
