### ISSUE TITLE
Photos tab FAQ improvements

### ISSUE THREAD

**Issue by rowo** [onaio/help#211]
- [ ] Would be nice to talk about the other controls on the top right if it's not too much trouble. There's full screen, zoom, share.
 
  ![screen shot 2016-11-03 at 1 00 52 am](https://cloud.githubusercontent.com/assets/1584163/19956281/0db584a0-a161-11e6-899a-a5a294c5a8f2.png)

- [ ] FAQ should be updated when downloading full res images is in: onaio/zebra#4727 (comment)

**Comment by faith-mutua** [comment]
Waiting for this issue https://github.com/onaio/zebra/issues/4734 to be closed before including info on the control buttons.

**Comment by rowo** [comment]
@faith-mutua there's no time table for the bug, so you could just update the help article for the second checkbox and create a new issue out of the first.

**Comment by faith-mutua** [comment]
@msschroeder, the [PR](https://github.com/onaio/help/pull/250) is ready fro review
