### ISSUE TITLE
Image width should be resized to max content width throughout help site

### ISSUE THREAD

**Issue by rowo** [onaio/help#22]

**Comment by wilo99** [comment]
will need to do a site-wide review then specify sizes for screenshots

**Comment by rowo** [comment]
No matter what size the images are they should be sized to fit the content. The site wide review should only help define the max resolution needed, and even then the image will probably resize no matter its resolution.

**Comment by wilo99** [comment]
This is already done, images do currently fit into their max-width and are centered. For the really wide screenshots, when fitting to content some details are not clear. E.g. 

**1. Wide image with browser fullscreen**

![screenshot-zebra ona io 2015-05-11 14-21-02](https://cloud.githubusercontent.com/assets/5087554/7563782/00950e1c-f7e9-11e4-938a-bdbf58341961.png)

**2. Wide image, but with browser resized to show more content**

![screenshot-zebra ona io 2015-05-11 14-20-30](https://cloud.githubusercontent.com/assets/5087554/7563783/03de493a-f7e9-11e4-9af5-a28740a6808a.png)

**Comment by rowo** [comment]
So should we just say things get resized down to max-width and otherwise just be centered?

**Comment by wilo99** [comment]
Yes, precisely

**Comment by rowo** [comment]
Ok closing if thats how it works. Thanks
