### ISSUE TITLE
Avoid social engineering/hacking and maintain privacy

### ISSUE THREAD

**Issue by rowo** [onaio/help#24]
Recently @ukanga shared an email address with someone who claims to not have been able to access an account. We should avoid this since it's sharing personal information with someone who isn't verified. This particular problem shouldn't actually occur again once beta is out since beta actually checks whether an email exists and this guy would've been notified that his email was wrong. There was also a case from a while ago that @pld mentioned.

We need a way to avoid this in the future. Perhaps @smusula can lead this process and/or come up with a few approaches. Maybe listing these situations in a doc, or having a training or a UI solution (like a different forgot password flow).

**Comment by rowo** [comment]
@smusula I started a doc for this. Slacked you the link.

**Comment by smusula** [comment]
@rowo this has been covered in the [faq](http://help.ona.io/faq/forgot-username-or-password/) too, if one responds to such an email the faq link should be helpful users too.

**Comment by rowo** [comment]
This is not covered in the FAQ because it's more of an internal policy issue for people that think they have the correct email and think the system is buggy. This is related to https://github.com/onaio/support/issues/10

I added this point as a section in the [Support Guidelines Doc](https://docs.google.com/document/d/1KxbaPxBZim5KUsksOXRGoCfxi1E2GEjTKFNX6EgVUQA/edit#heading=h.3jy589wg55s) so this issue is mainly about making sure everyone knows how to handle these issues if they are assigned to them. You can close it if this is the case.

**Comment by smusula** [comment]
@rowo I've provided the links on the [support repo](https://github.com/onaio/support)  for internal use. I'll also notify everyone via emai about these links on the repo.
