### ISSUE TITLE
Identify pages that will need to be updated after new pricing is implemented

### ISSUE THREAD

**Issue by cafootitt** [onaio/help#246]
Once new pricing is implemented, we'll need to update all relevant pages on the help site. Can the help site team identify all pages that reference free or paid plans or reference any features as premium, etc.? Exact updates to the content will come in a later issue; this is just to identify what all will need to be updated.

**Comment by msschroeder** [comment]
Pricing pages identified: https://help.ona.io/guides/user-accounts/, https://help.ona.io/faq/general-FAQ/ - Changes have been made.

**Comment by msschroeder** [comment]
Closed with pull request #258 and #257
