### ISSUE TITLE
Update Import CSV FAQ

### ISSUE THREAD

**Issue by rowo** [onaio/help#27]
update to say: Import CSV only works for forms without data.

From https://github.com/onaio/zebra/issues/1939

**Comment by rowo** [comment]
@mberg made this high priority and added a milestone — this is related to SDI's needs in general

**Comment by cagulas** [comment]
Also, the UTF encoding seems to be an issue that comes up fairly often from users, and I think we can expect a lot of our users to create csv files from Microsoft Excel, so in the documentation, should also explain how csv files created through excel are not compatible and the workaround (i.e., upload to google sheets first).  I can write this content.  Please let me know if there is a draft you are working on somewhere.

**Comment by rowo** [comment]
@cagulas I have not yet started a draft. The main thing I'm going to update is around saying you can only upload data to an empty form. Does the UTF issue still apply there?

**Comment by cagulas** [comment]
Yes, it does.  I can work on some text and send it to you to incorporate.

**Comment by rowo** [comment]
Done, http://help.ona.io/faq/import-data/
