### ISSUE TITLE
Set up wordpress on stage-help.ona.io

### ISSUE THREAD

**Issue by rowo** [onaio/help#271]
This issue is just about [getting Wordpress set up](https://codex.wordpress.org/Installing_WordPress). The sooner we do this the better since there's a backup file from end of last year that we can use and the more time that passes, the more that needs to be redone.

- permissions that allow admins to add new themes
- perhaps something different than what @pld had done previously which had very strict permissions and caused some issues with a backup plugin

**Comment by pld** [comment]
Info on the current last setup is here, https://github.com/onaio/playbooks/blob/master/docs/wordpress.md

One thing that may miss is ways to build full backups
