### ISSUE TITLE
Update the summary charts with new chart features in data management guide

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#276]
Feature updates:
Support for three variables in a chart: https://github.com/onaio/zebra/issues/4981
Ability to toggle no/null answers on charts: https://github.com/onaio/zebra/issues/4982

Area to be updated: https://help.ona.io/guides/data-management/#summary-charts

**Comment by msschroeder** [comment]
@faith-mutua This might be helpful. I did this quickly for WFP:  https://docs.google.com/document/d/1PZxK-Ato4LrSr28aBYxfURZT4U5v8fBbNklMle8apW8/edit?usp=sharing

**Comment by faith-mutua** [comment]
@msschroeder this has been done and published.

**Comment by msschroeder** [comment]
@faith-mutua Is it just a number by two select_one variables? It thought you can disaggregate by number and select_one questions in any order? Also, it says that you can only disaggregate by select_one variable.

**Comment by faith-mutua** [comment]
@msschroeder I made some edits to the documentation. Please take a look
