### ISSUE TITLE
The new help site only displays one article per category, but there are multiple articles per category

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#284]
The new help site: help-stage.ona.io is exhibiting weird behaviour:

What is occurring: Only one article will appear for each category while multiple articles may have the same categorization applied. For example, "Premium Features" only include the article Ona Apps, but should also include Filtered datasets and XLS Reports. 

What is expected: Each category will display the article(s) with that applied category.

**Comment by rowo** [comment]
@msschroeder do you know when this started happening? This is the type of bug we can submit to the theme creators if we know potential causes.

**Comment by rowo** [comment]
@msschroeder Fixed this. Updated the theme and plugins. I think it was just a mismatch in versions.

**Comment by msschroeder** [comment]
@rowo Barbara noticed it last week. But my guess it might have been since we have reuploaded everything. However, I cannot say with certainty because I was more focused on getting the material uploaded than how it look initially.
