### ISSUE TITLE
When clicking on side menu, update URL to include anchor link

### ISSUE THREAD

**Issue by rowo** [onaio/help#286]
Will make it easier for support team to share links

**Comment by rowo** [comment]
I emailed the wordpress theme support team (who would be the only ones able to make this change). Waiting to hear back.

**Comment by rowo** [comment]
@msschroeder @bmalina @faith-mutua Here's the feedback from the theme support person on this.

> That's something we can look into and I have made a note on our product tracker to investigate.
> In the meantime, instead of viewing the source for the headers to generate a link, you can maybe get the team to copy the link from the TOC widget directly, by right clicking and copying the url (I've attached a screenshot for reference)
> ![knowall-toc-link-copy](https://cloud.githubusercontent.com/assets/1584163/25773229/417cc26c-3248-11e7-858a-381f55e4ae78.png)

**Comment by msschroeder** [comment]
@rowo Thanks for checking into this. This is quite helpful.
