### ISSUE TITLE
Update Export Documentation with redesign of exports

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#289]
Please update the following documents on the help site:
- [ ] https://help.ona.io/knowledge-base/guide-ona-apps/#2-direct-export-to-google-sheets
- [ ] https://help.ona.io/knowledge-base/data-management/

**Comment by faith-mutua** [comment]
@msschroeder I updated the data management guide with content on the redesigned data exports. Please check.

**Comment by msschroeder** [comment]
@faith-mutua The data management guide looks good. We just have the Google Sheets left

**Comment by faith-mutua** [comment]
@msschroeder I have updated the Google Sheets section

**Comment by msschroeder** [comment]
@faith-mutua I have just check the Google authentication. It says that you can check how to authenticate, but it goes to a previous section and this does not authenticate the same as it does when you try it. Can we update the authentication section.
