### ISSUE TITLE
Create a Google Analytics Page for the help.ona.io Wordpress site

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#290]
Currently, there is no google analytics page for the help site. We would like to add this to help with measuring metrics as a support team moving forward. Would this just require finding a good google analytics plugin or just setting up the site?

**Comment by rowo** [comment]
@msschroeder We can do the analytics plugin route or header/footer edit plugin, they both seem common. Have you been using the metrics in Knowledge Base > Analytics?

**Comment by msschroeder** [comment]
I am closing this as Intercom with the Analytics on this help site has most of the metrics we need.
