### ISSUE TITLE
Create XLSReport documentation in a Google doc

### ISSUE THREAD

**Issue by pld** [onaio/help#30]
*  brief overview of xlsreports are
* template example
* where to upload
* where to download

From this page:
http://jxls.sourceforge.net/samples/tagsample.html

Cover:
* tags
* loops
* functions ie) $[SUM]

**Comment by mberg** [comment]
From this page:
http://jxls.sourceforge.net/samples/tagsample.html

Cover:
* tags
* loops
* functions ie) $[SUM]

**Comment by pld** [comment]
@kiambuthi FYI this is milestoned for April 24th

**Comment by kiambuthi** [comment]
@pld Will work on the documentation and get back on time

**Comment by kiambuthi** [comment]
@pld Here is the XLS Reports documentation:

https://docs.google.com/a/ona.io/document/d/11TvJH9Bk25QBJ_U1YhSMKavnwFT2_5K9CnzvhQ_uUrI/edit?usp=sharing

@smusula @cagulas are doing final reviews on the documentation
