### ISSUE TITLE
Add content on how to pull data from repeat groups

### ISSUE THREAD

**Issue by faith-mutua** [onaio/help#307]
This information should be added to the Linked dataset [help guide](https://help.ona.io/knowledge-base/how-do-i-link-a-dataset-as-a-media-file-to-another-form/).

**Comment by faith-mutua** [comment]
Done. @msschroeder please review the [guide ](https://help.ona.io/knowledge-base/how-do-i-link-a-dataset-as-a-media-file-to-another-form/#pulling-data-from-a-repeat-group)

**Comment by msschroeder** [comment]
@faith-mutua is it possible to see the google guide for this. I prefer for the first draft at the minimum to to be a google sheet and then we move to placing on the site unless this has been previously reviewed by at least one other person than myself.

**Comment by faith-mutua** [comment]
@msschroeder here is the [link](https://docs.google.com/document/d/11moawtyhRLT98XznnBj-VSfHxJcmj0N-T_ME80icEWQ/edit?usp=sharing) to the Google doc.

**Comment by msschroeder** [comment]
@faith-mutua I have made some comments in the Google Doc
