### ISSUE TITLE
Add screenshots to Data Collection Guide

### ISSUE THREAD

**Issue by smusula** [onaio/help#32]
* Use Skitch to highlight the images
* Use the default skitch colour
* Use the Starter Forms as examples

**Comment by cagulas** [comment]
hi @smusula wanted to give you an update on my progress before I finish work today.

I've edited the content and inserted screenshots up to the ODK Collect section.  The screenshots are all uploaded in the content/screenshots folder.  My work is on a separate branch called cagulas-data-collection-guide.  I'll continue where I left off on Monday and submit a pull request when I'm finished.j

Thanks!

**Comment by smusula** [comment]
@cagulas thanks for working on this:

 I've reviewed your work and I have a recommendation;  for the screenshots can we use one form across the entire guide for consistency either Tutorial or Baseline Household Survey.

Thanks.

**Comment by cagulas** [comment]
Ok, am finished with this data collection guide.  I can easily replace the screenshots, but would be easier if you pushed this to master first, so I can see what screenshots need to be replaced.
