### ISSUE TITLE
Create an faq on on the various ways of uploading form

### ISSUE THREAD

**Issue by smusula** [onaio/help#33]
Write documentation on the various ways of uploading forms

* From local drive
* External url
* Dropbox

**Comment by cagulas** [comment]
https://docs.google.com/document/d/12uu3D13gHS6k4HS-tbc8K0fOjAz4Ytdg7jbvtO6Urqo/edit

Done.  See link above.  If this looks ok @smusula I can add the images to the repo.  Let me know.

**Comment by cagulas** [comment]
Ok, images are added to github and I've specified the image file name in the upload form documentation.
