### ISSUE TITLE
Change favicon on help site

### ISSUE THREAD

**Issue by cagulas** [onaio/help#34]
Change to new Ona logo.

**Comment by wilo99** [comment]
closed by https://github.com/onaio/help/commit/5cd8496880a08f9329f87f0e4bea63a0d41ce0a2

**Comment by cagulas** [comment]
I'm still seeing the old logo.  Actually, I see the old logo as the favicon for all of our Ona web pages...blog, company, etc.

**Comment by wilo99** [comment]
try a hard refresh CMD+Shift+R, images may have cached

**Comment by pld** [comment]
company and blog still have the old logo, help has the new one

**Comment by cagulas** [comment]
Thx, that worked.
