### ISSUE TITLE
Add the project's and organization guide designs

### ISSUE THREAD

**Issue by smusula** [onaio/help#35]
Create designs for the [projects](http://help.ona.io/guides/projects/) and [organization](http://help.ona.io/guides/organizations/) guides.

**Comment by wilo99** [comment]
Likely across all pages, changes in CSS will reflect site-wide, fyi noted points need to be highlighted like [here](http://docs.nativescript.org/hello-world/hello-world-ns-cli.html)

**Comment by wilo99** [comment]
@smusula Is this the same as #71 ?

**Comment by rowo** [comment]
Just merged a PR with some icons for this stuff. I guess the next step is to unhide, so assigned to @wilo99
