### ISSUE TITLE
Change toggl project to help site instead of knowledge base

### ISSUE THREAD

**Issue by cagulas** [onaio/help#38]
Currently when time-tracking on toggl, it says Ona Knowledge Base.  There is also an option for Support Site. Can these be merged?  Can we change the label to Help Site or something similar?

**Comment by rowo** [comment]
That would be clearer. Is that something you can do or does it have to be someone with other permissions?

**Comment by cagulas** [comment]
Cool.  I'll see if I can do this myself.  If not, will comment here.

**Comment by smusula** [comment]
@cagulas , @rowo There is a project **Support Site**, no need to create a new one. Been using this to track my time on the help site

**Comment by cagulas** [comment]
Hey, I wasn't planning to create a new one.  I was checking to see if the Support Site and Knowledge Base projects can be merged and renamed as Help Site.  For instance, we don't need a separate Knowledge base project on toggl, but if no one is tracking time there, then we can probably delete this one.

**Comment by rowo** [comment]
@cagulas makes sense. Were you able to delete the knowledge base one?

**Comment by cagulas** [comment]
No, I don't have the permissions to do this.   I just checked.  For instance, I don't have any of the editing options when I click on a project, see this link: http://support.toggl.com/projects-overview/#editingprojects

I see that Knowledge base has about 29 hours tracked on it, so it should be archived instead of deleted.

**Comment by rowo** [comment]
@mberg can you either merge the Support Site project with the Knowledge Base project *or* archive Knowledge Base and we can just used Support Site?

**Comment by mberg** [comment]
Archived knowledge base.
