### ISSUE TITLE
Update ODK Briefcase documentation

### ISSUE THREAD

**Issue by cagulas** [onaio/help#39]
We're getting quite a few support emails about using ODK Briefcase, and I think the instructions need to be updated on the help site.  For example, is the url now odk.ona.io/[username]?

Answers to frequent error messages as reported by users.  For example, provide common error messages and what they usually mean, how to fix them.

**Comment by smusula** [comment]
@cagulas there an open issue for it [https://github.com/onaio/help/issues/37](https://github.com/onaio/help/issues/37) that will cover the above.

**Comment by cagulas** [comment]
Woops, don't know how I missed that, because I scanned the entire list!
