### ISSUE TITLE
Create documentation on Forms

### ISSUE THREAD

**Issue by smusula** [onaio/help#56]
Create documentation on forms. Work on a shared google doc in the [forms](https://drive.google.com/a/ona.io/folderview?id=0BzZ4hMHTat-YfldzdkVvVnVGVVFpcmVMREZPWVRLZzFZRl9iWV92VnhzQ2ZPOVN2SzlZaG8&usp=sharing) folder.

- [x] Adding media to forms in Ona (images, videos,audio) - use the [Birds xlsform](https://docs.google.com/a/ona.io/spreadsheets/d/1FPe7sRfmfz75eds0aJ3XiviaA6BJRTchHa27rtby7VM/edit?usp=sharing)
  *  How do I include media files in my xlsform?
 * What type of media files are supported in Ona?
 * Where do I upload the media files referenced in my xlsform?
- [x] Managing Forms:
  * How to Delete forms
 * How to make forms Inactive (explain why this function might be useful apart from not being able to accept submission)

Please refer to the [documentation collaboration](https://github.com/onaio/help#documentation-collaboration) for guidelines on what is expected.

**Comment by smusula** [comment]
@kiambuthi make changes as per the comments in the Google doc, let @cagulas make the final review then close the issue once everything has been deemed ok.

**Comment by kiambuthi** [comment]
@cagulas. I have shared the document with you. Have a look at how I adressed @smusula comments and feel free to add anything you deem fit or needs to be polished up.

**Comment by cagulas** [comment]
Have reviewed and made some further edits.  Looks good to me.  To be discussed is whether to create a separate documentation for media question types or include both topics in this documentation.  Thoughts?

**Comment by ndisha** [comment]
@cagulas @kiambuthi I agree with Carolyn, we should split this document into:
1. XLSForms management on Ona
2. Media question types
Looks good to me too!

**Comment by kiambuthi** [comment]
@cagulas I have reviewed all the comments you pointed out on the documentation; advice on the next process.

I also share the same views highlighted by you and @ndisha 

Thanks.

**Comment by cagulas** [comment]
Ok, great.  I have cleared up all the comments in this documentation.  It's clean now and ready to be converted to markdown.  @kiambuthi are you familiar with markdown syntax?  Would you be able to take the first stab at this by creating a new branch (pls label the branch after the issue number) and putting this documentation down as a new faq page?  You can use an existing faq page as a template.

**Comment by cagulas** [comment]
Also, have created a new issue (#62) that covers the media question type documentation.  This documentation can be written in the same google document, but it's a separate issue, so this issue can be closed once the content is up on the site.

**Comment by kiambuthi** [comment]
@cagulus. I am not familiar with markdown but @wilo99 has offered to assist me in putting this documentation as a new faq page. 

Seen the new issue and will work on it as well.

**Comment by rowo** [comment]
@kiambuthi it would be good to familiarize yourself with markdown

**Comment by kiambuthi** [comment]
@rowo Sure, I will work to grasp this skill (https://docs.google.com/spreadsheets/d/1GvfHRvn_eG84HG_VphRf86SwmcrkwDmS324vxL5aaNg/edit#gid=1178600447)

**Comment by rowo** [comment]
@kiambuthi Rather than waiting to Q3, I recommend just building it into your process and trying it out. One way to start is to duplicate a .md file from the support page repo and work from that. If you run into problems, Google has all of the answers and/or reach out to anyone on the team. Ask myself, William, Sylvia, or Carolyn if you have any questions. The support page files have some extraneous stuff at the top that aren't markdown.. they are just instructions on where the files go. Ask us if you have questions. Try it out!

**Comment by kiambuthi** [comment]
@rowo I will rise up to the challenge. Will definitely consult in case of any challenge encountered.

**Comment by kiambuthi** [comment]
@cagulas @smusula there is a pull request for this documentation https://github.com/onaio/help/pull/66
