### ISSUE TITLE
Add hosting security information

### ISSUE THREAD

**Issue by mberg** [onaio/help#57]
Probably want to add this to Ona site too.  
- Data from phone to server is transmitted over an SSL encrypted server.
- Access the site is secured by SSL the same technology you trust when doing online banking
- Our servers are ISO 27001 (http://aws.amazon.com/compliance/iso-27001-faqs/). grab languagr from that
- Mention forms are not encrypted by default but can be if you follow this: http://help.ona.io/faq/encrypted-forms/

**Comment by msschroeder** [comment]
Closed with #195

**Comment by mberg** [comment]
Is this up on the site anywhere?  It should be a page on the main site that
we can refer from product features page and maybe even footer

**Comment by msschroeder** [comment]
@mberg I am writing a Security FAQ for our documentation. Peter has reviewed. Left a comment about the SSL related points as I believe they have been updated with TSL.
