### ISSUE TITLE
Create Managing accounts documentation

### ISSUE THREAD

**Issue by smusula** [onaio/help#60]
Create documentation on Accounts. Work on a shared google doc in the [user-accounts](user-accounts guide) folder.

The content should cover the following:

- [x] Accounts
 * Setting up my public profile
- [x] Manage Account
 * How do I change my password?
 * How do I change the email address on my account?
 * How can I delete my Ona account?

**Comment by smusula** [comment]
@kiambuthi this documentation needs to be redone. Please read through the comments I've made on the Google doc. Ask @cagulas if you need any clarification or assistance in anything.

**Comment by kiambuthi** [comment]
@cagulas I have shared the documentation with you. Your review will be highly appreciated.

Thanks.

**Comment by cagulas** [comment]
Just reviewed.  You can check out my comments.  Thx.

**Comment by kiambuthi** [comment]
@cagulas I have addressed the comments. Thanks.

**Comment by cagulas** [comment]
hey @kiambuthi looking good.  Made some additional very minor comments.  Once you address those, I think this can start being converted to markdown as well.  You can create a separate branch for this issue and starting putting the content in.  Thanks.

**Comment by kiambuthi** [comment]
@cagulas Hi, check out how I addressed the comments shared

**Comment by cagulas** [comment]
Ok, am done.  Reviewed the entire document once more as well.  Everything looks good.  @smusula if everything looks ok to you, this can be converted to markdown.  Is this going to be an faq or a guide?

**Comment by smusula** [comment]
@cagulas this is is going to be the user accounts guide. @kiambuthi address comments made on the doc.

**Comment by kiambuthi** [comment]
@smusula @cagulas I have addressed the comments shared. Have a look.

**Comment by cagulas** [comment]
@kiambuthi have just discussed this with @smusula and you can create a separate branch and start converting this to markdown now.  The issues that remain are around screenshots, so screenshots can be added at the end.  You can create the placeholders for the screenshots for now.  Are you ok to start creating this markdown file?

**Comment by kiambuthi** [comment]
@cagulas am okay with creating a markdown file.

**Comment by kiambuthi** [comment]
@smusula @cagulas there is a pull request for this documentation https://github.com/onaio/help/pull/65
