### ISSUE TITLE
Create documentation on Repeats

### ISSUE THREAD

**Issue by smusula** [onaio/help#61]
Use the [Baseline Survey](https://docs.google.com/spreadsheets/d/10LpWAr7dzlcUjO3BiFWu4ez3TDJUn83VvNkIn8RGdXk/edit?usp=sharing). The documentation should include:
- [ ] Indexed repeats
 * how indexed-repeat works;
 * use the position();

- [ ] Repeat groups
 * calculation of a total from value within repeat group;
 * how to sum up answers from all repeat groups - Using the sum(), count() functions

- [ ] Nested repeat groups

You can also refer to: https://docs.google.com/spreadsheets/d/1GplcITCzZNT_9nwG5CFBhqKzj9k5PWkYx3id_STmriA/edit?usp=sharing

**Comment by kiambuthi** [comment]
@cagulas have a look at the documentation and share your views

**Comment by kiambuthi** [comment]
@smusula @cagulas. There is a pull request for this. You can have a lookhttps://github.com/onaio/help/pull/68

**Comment by kiambuthi** [comment]
@smusula @cagulas The repeat documentation can be found here: https://docs.google.com/document/d/1dQtGwyxBe5pV5IohYIHQq8F7IxRby-9IkcYEVB6R2nY/edit

**Comment by kiambuthi** [comment]
@smusula documentation on nested repeat can be found here: https://docs.google.com/document/d/1dQtGwyxBe5pV5IohYIHQq8F7IxRby-9IkcYEVB6R2nY/edit

**Comment by jmunene** [comment]
@smusula I will use an example of household roster/ questions.

**Comment by smusula** [comment]
Done: https://docs.google.com/a/ona.io/document/d/1dQtGwyxBe5pV5IohYIHQq8F7IxRby-9IkcYEVB6R2nY/edit?usp=sharing closed by this PR: https://github.com/XLSForm/xlsform.github.io/pull/61
