### ISSUE TITLE
Documentation on media question types and viewing multimedia data on Ona

### ISSUE THREAD

**Issue by cagulas** [onaio/help#62]
Topics:
- Short overview of the 3 media question types (image, audio, video) and how they function in a form (both ODK Collect and Enketo)
- How users may need to install an audio recording app in order to collect audio data in a form (e.g., if their mobile device does not have a default audio recorder)
- Mention ODK Briefcase and how it can be used in low bandwidth settings to upload media data that is included with the form data
- Viewing image, audio, and video data in beta Ona and how to extract or download this data from Ona

**Comment by cagulas** [comment]
Please work from the existing form document; I have added a new section at the bottom: https://docs.google.com/document/d/1uJAxnZnylNq00Nnu101c-UsBraa1xqoFRbx7G8MkXMo/edit

**Comment by smusula** [comment]
@kiambuthi I've added comments to the above doc, please address them.

**Comment by kiambuthi** [comment]
@smusula I have reviewed your comments and introduced made comments as well. Please review and feel free to resolve the issues that have been adequately adressed.

**Comment by kiambuthi** [comment]
Hi @smusula @cagulas There is a pull request for this documentation https://github.com/onaio/help/pull/67
