### ISSUE TITLE
Finalize documentation on preparing Android phones for data collection

### ISSUE THREAD

**Issue by smusula** [onaio/help#64]
@kiambuthi please finalize the guide on the things you should do to the devices to prep them for use solely as data collection devices:

https://docs.google.com/a/ona.io/document/d/1uQecO5bHd8ADUJXmkFBl5UdNPvUiByjfi_7XcTAiuLU/edit?usp=sharing

I've made some suggestions and edits on the document.

This is basically what we do when configuring devices for our clients. Save the Children would like to do this by themselves, therefore,  we need to provide a guide on how this is done, so that their project managers can set up their devices by themselves.

**Comment by kiambuthi** [comment]
@smusula I have addressed the comments you had shared. Have a look and get back .https://docs.google.com/document/d/1uQecO5bHd8ADUJXmkFBl5UdNPvUiByjfi_7XcTAiuLU/edit

**Comment by kiambuthi** [comment]
@smusula I have addressed the comments you had shared. Have a look and get back .https://docs.google.com/document/d/1uQecO5bHd8ADUJXmkFBl5UdNPvUiByjfi_7XcTAiuLU/edit

**Comment by kiambuthi** [comment]
@smusula @cagulas Awaiting @cagulas to review my comments to the issues she had raised. As soon as she checks out my comment; I will proceed https://docs.google.com/document/d/1uQecO5bHd8ADUJXmkFBl5UdNPvUiByjfi_7XcTAiuLU/edit

**Comment by cagulas** [comment]
Have responded to all of your comments @kiambuthi

**Comment by kiambuthi** [comment]
@cagulas Check out my response to your comments

**Comment by cagulas** [comment]
Done.

**Comment by kiambuthi** [comment]
@cagulas @smusula Check out my feedback on your comments. Fell free to resolve comments; if they have been addressed appropriately

**Comment by cagulas** [comment]
@kiambuthi as discussed over slack, you can proceed with finishing writing the guidelines content, keeping in mind that this should be a generalized protocol, not specific to any one project or phone.  Please use the information we've provided in the comments to guide your writing.  Once you have written the rest of the content, we'll be able to close these comments.  Thanks.

**Comment by kiambuthi** [comment]
@cagulas I have removed the links to the other documentation as we had discussed over slack. @smusula  @cagulas Check out the documentation and feel free to resolve comments that you deem to have been resolved fully. Thanks
