### ISSUE TITLE
Documentation / Overview on how Orgs work

### ISSUE THREAD

**Issue by mberg** [onaio/help#69]
We need a detailed overview of how Orgs, org members and projects work

This should be for the help site but packaged up in a blog post.

**Comment by rowo** [comment]
@mberg [How do I use organizations](http://help.ona.io/faq/how-do-i-use-organizations) is up on the help site now. Can you be more specific on what needs to be added to this? By "detailed" are you talking about something more step-by-step and more content like the [New to Ona guide](http://help.ona.io/guides/getting-started/)?

**Comment by smusula** [comment]
@mberg @jmunene will work on this this week. @rowo we're going to work on a detailed guide on organization which will have screen shots and step by step instructions that will cover the following subtopics:

 - [ ]  What is an organization?
- [ ]  Adding org members (organization members)
- [ ]  Organization Settings (Org description, Org Profile)
- [ ]  Creating org projects
- [ ] Org Projects permissions

@jmunene refer to the [help](https://github.com/onaio/help) repo for guidelines on how to add content to the help site. 

Note:

Use Google Docs for documentating sections before adding to Markdown. Google doc content should be saved in their specific guide folder as indicated [here](https://drive.google.com/a/ona.io/folderview?id=0BzZ4hMHTat-YaTctUVF5Z25JYTg&usp=sharing).

**Comment by rowo** [comment]
@mberg @smusula ok, guess someone can "package up for a blog post" later on. I imagine that will be more highlights/benefits focused than a guide.

**Comment by rowo** [comment]
Guess we can separate out the org guide and modify the FAQ page into a "why use orgs" kind of page, along with adding that to the blog. 

CG: 
>the main benefits I see are: 1) multiple admins per project as opposed to just one; and 2) org level permissions that make it easier to assign grouped permissions instead of individually.  And maybe 3) just a more polished, professional looking org home page
