### ISSUE TITLE
Create designs for forms, user-accounts guides

### ISSUE THREAD

**Issue by smusula** [onaio/help#71]
Create designs for the [forms](http://help.ona.io/guides/forms/) and user-accounts guidse then unhide both guides.

**Comment by rowo** [comment]
@smusula Just want to confirm, the user accounts guide is the [managing accounts doc](https://docs.google.com/document/d/1bN_5WfyIBO2o2DfWYFdR8rS_xJpnjn5PrMDox9gxQ2M/edit)?

**Comment by smusula** [comment]
@rowo yes, [http://help.ona.io/guides/user-accounts/](http://help.ona.io/guides/user-accounts/)

**Comment by rowo** [comment]
@smusula @wilo99 I made some quick icons for forms and accounts in gh-pages

**Comment by wilo99** [comment]
ok, @rowo , I'll add those in today

**Comment by wilo99** [comment]
@rowo, I can't locate the icons on drive, which folder are they in?

**Comment by wilo99** [comment]
nm, just saw them in the image folder
