### ISSUE TITLE
Add data management guide

### ISSUE THREAD

**Issue by smusula** [onaio/help#76]
Add the data management guide, the guide should cover subtopics listed in [this doc ](https://docs.google.com/a/ona.io/document/d/14Y6CwTzZv1UnwyPM-u67SWU5OvA3apOSVnqm2Cb2UrI/edit?usp=sharing). Refer to the help repo for guidelines on how to add content to the help site.

Note:
Use Google Docs for documenting sections before adding to Markdown. Google doc content should be saved in their specific guide folder as indicated [here](https://drive.google.com/a/ona.io/folderview?id=0BzZ4hMHTat-YaTctUVF5Z25JYTg&usp=sharing).

**Comment by smusula** [comment]
Add content about metadata fields displayed on the data table and exports i.e (_duration, _version, _submitted_by, _tags, _uuid)

**Comment by skambo** [comment]
@faith-mutua Please add on for the edit chart title feature (editing on charts saved to the 


Below are the permissions for this feature

- [ ] Can view - can't save to dashboard and can't edit 

- [ ] Can view and download - can save to dashboard but cant edit - has an open issue https://github.com/onaio/zebra/issues/4685

- [ ] Can submit - can save to dashboard and can edit - has an open issue https://github.com/onaio/zebra/issues/4685

- [ ] Can edit - can save to dashboard and can edit 

- [ ] Admin - can save to dashboard and can edit. 

Ref 
https://github.com/onaio/zebra/pull/4651

**Comment by skambo** [comment]
@faith-mutua Might it be necessary to elaborate on the Map items below ( Mapbox is now called 'Mapbox Streets' and there's the newly added digital globe basemap layer at the bottom)

<img width="595" alt="screen shot 2016-11-02 at 11 33 01 am" src="https://cloud.githubusercontent.com/assets/4996911/19921721/5257dc0a-a0f0-11e6-8733-a1d7a83912a0.png">

**Comment by faith-mutua** [comment]
@skambo, yes, sure, I will update all the details in the guide

**Comment by rowo** [comment]
@msschroeder data management icon

![data-management](https://cloud.githubusercontent.com/assets/1584163/23046956/c04fea94-f47a-11e6-9c2f-73dd8a2e2882.png)
