### ISSUE TITLE
Add anchor points support to headers of large documents

### ISSUE THREAD

**Issue by smusula** [onaio/help#79]
Add anchor points to headers of large faq documents

**Comment by wilo99** [comment]
Useful: http://milanaryal.com/2015/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/

**Comment by msschroeder** [comment]
Put on hold with possible transition to new help site - May be able to incorporate with transition

**Comment by rowo** [comment]
@msschroeder the cool thing about the wordpress site is it seems to create id's automatically to headers, making anchor links possible to any header

**Comment by msschroeder** [comment]
Closing issue as new help site will incorporate this feature
