### ISSUE TITLE
Forward old org faq page to new org guide page

### ISSUE THREAD

**Issue by cagulas** [onaio/help#87]
The old org faq page, http://help.ona.io/faq/how-do-i-use-organizations/, is now out of date.  We have our new org guide instead, http://help.ona.io/guides/organizations/.

Since we have used the old faq page for the past several months in responding to sales emails, we need to keep this url up, but it should forward to the new org guide instead.

Assigning to @smusula, but please reassign if needed.

**Comment by rowo** [comment]
Are we able to forward from FAQs directly? I'm in favor of having a brief overview.. like 2 minutes most important stuff, then linking to the guide.

**Comment by cagulas** [comment]
Ok, that sounds like a good approach.
