### ISSUE TITLE
Hide advanced users documentation

### ISSUE THREAD

**Issue by cagulas** [onaio/help#91]
http://help.ona.io/guides/advanced-users/

This content isn't written yet, so this page should be hidden.  One user already discovered it and sent it to us.

**Comment by rowo** [comment]
From WLM: This isn't shown on the help homepage. Not sure how they got to it. @cagulas do you know?

**Comment by wilo99** [comment]
Is there a link to it on Zebra maybe?

**Comment by cagulas** [comment]
Not sure, he didn't say, but I just tried searching for 'api' in the search box on the help site, and google search results returned this page as the first result, so I'm betting that's how he found it.

**Comment by wilo99** [comment]
I think I can unpublish it for now or add it to a drafts, hopefully that will sort it out

**Comment by rowo** [comment]
closed by https://github.com/onaio/help/pull/92
